---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: secureflop
description: This is a silverblue-nvidia-hardened image without gnome

base-image: ghcr.io/secureblue/silverblue-nvidia-hardened
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: signing

  - type: default-flatpaks
  configurations:
    - notify: true
      scope: system
      install:
        - org.signal.Signal
        - com.bitwarden.desktop
        - com.vscodium.codium
        - app.grayjay.Grayjay
    - scope: user
  
  - type: dnf
    install:
      install-weak-deps: false
      packages:
        - fcft
        - neovim
        - fcft-devel

    remove: 
      auto-remove: true
      packages: 
        
