---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: secureflop
description: base-main extension

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: signing

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.signal.Signal
          - com.bitwarden.desktop
          - com.vscodium.codium
          - app.grayjay.Grayjay
      - scope: user

  - type: dnf
    install:
      install-weak-deps: false
      packages:
        - fcft
        - wofi
        - tmux
        - foot
        - htop
        - swaybg
        - neovim
        - wlroots
        - swayidle
        - swaylock
        - wlr-randr
        - fcft-devel
        - pipewire
        - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

  - from-file: common/nvidia.yml

  - type: script
    scripts:
        - httpsmirrors.sh
        - installselinuxpolicies.sh
      
        - regenerateinitramfs.sh
        - removesuid.sh
        - enable-preset-services.sh

    
